import Head from 'next/head'
import Image from 'next/image'
import CreationSection from '../components/MainPage/CreationSection'
import InteractiveVrSection from '../components/MainPage/InteractiveVrSection'
import MainSection from '../components/MainPage/MainSection'
import Footer from '../components/Footer'
import Menu from '../components/Menu'

export const getStaticProps = async () => {

  const data=[
    {
        title:'Deep Earth',
        mobileUrl:'/images/mobile/image-deep-earth.jpg',
        desktopUrl:'/images/desktop/image-deep-earth.jpg'
    },
    {
        title:'Night Arcade',
        mobileUrl:'/images/mobile/image-night-arcade.jpg',
        desktopUrl:'/images/desktop/image-night-arcade.jpg'
    },
    {
        title:'Soccer Team Vr',
        mobileUrl:'/images/mobile/image-soccer-team.jpg',
        desktopUrl:'/images/desktop/image-soccer-team.jpg'
    },
    {
        title:'The Grid',
        mobileUrl:'/images/mobile/image-grid.jpg',
        desktopUrl:'/images/desktop/image-grid.jpg'
    },
    {
        title:'From Up Above Vr',
        mobileUrl:'/images/mobile/image-from-above.jpg',
        desktopUrl:'/images/desktop/image-from-above.jpg'
    },
    {
        title:'Pocket Borealis',
        mobileUrl:'/images/mobile/image-pocket-borealis.jpg',
        desktopUrl:'/images/desktop/image-pocket-borealis.jpg'
    },
    {
        title:'The Curiosity',
        mobileUrl:'/images/mobile/image-curiosity.jpg',
        desktopUrl:'/images/desktop/image-curiosity.jpg',
    },
    {
        title:'Make It Fisheye',
        mobileUrl:'/images/mobile/image-fisheye.jpg',
        desktopUrl:'/images/desktop/image-fisheye.jpg'
    }
];

  return {
      props: {creations:data}
  }
}

export default function Home({creations}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Alata&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300&display=swap" rel="stylesheet"></link>
      </Head>
      {/* <Menu/> */}
      <MainSection></MainSection>
      <div className='px-5 py-24'>
        <InteractiveVrSection></InteractiveVrSection>
        <CreationSection creations={creations}></CreationSection>
      </div>
      {/* <main className='h-screen bg-gray-800 bg-mobile-image-hero bg-cover bg-no-repeat sm:bg-desktop-image-hero'>
        pokemon
      </main> */}

      <Footer></Footer>
    </div>
  )
}
